#!/usr/bin/env ruby

require 'optparse'
require 'csv'
require 'time'

options = {
  list: %w(CNY)
}
OptionParser.new do |opts|
  opts.banner = "Usage: fetch_currencies.rb [options]"

  opts.on("--no-fetch", "Skip data download from BIS") do
    options[:skip_fetch] = true
  end

  opts.on("--currencies x,y,z", Array, "Specify a list of currencies, such as CNY, to fetch") do |list|
    options[:list] = list
  end

  opts.on("--list-currencies", "List currencies") do
    options[:list_only] = true
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

unless options[:skip_fetch]
  ZIP_URL = 'https://www.bis.org/statistics/full_webstats_xru_current_d_dataflow_csv_row.zip'

  system "wget #{ZIP_URL} -N -O ~exchange.zip -q --show-progress"
  system "unzip ~exchange.zip"
  system "mv WEBSTATS_XRU_CURRENT_D_DATAFLOW_csv_row.csv ~exchange.csv"
end

system "mkdir -p prices/currencies/"

line = -1
cols = []

CSV.foreach("~exchange.csv") do |row|
  line += 1
  if cols.empty?
    if line == 2
      row.each_with_index do |cur, i|
        options[:list].each do |x|
          if options[:list_only]
            puts cur
            next
          end
          next unless cur.start_with? x
          puts "Found #{cur}"
          cols << {
            index: i,
            name: x,
            file: File.open("prices/currencies/#{x}.daily.prices.ledg", "w")
          }
        end
      end

      exit if options[:list_only]

      cols.each do |o|
        o[:file].puts "; Auto generated by fetch_currencies.rb on #{Date.today.to_s}"
      end
    elsif line > 2
      puts "Error: No currencies found"
      exit 1
    else
      next
    end
  end

  date = row[0]
  next unless date =~ /^\d{4}-\d\d-\d\d$/

  cols.each do |o|
    x = row[o[:index]].to_s
    next unless x.to_f > 0
    o[:file].puts "P #{date} $    #{x.ljust 10} #{o[:name]}"
  end
end
