var Sugar;
{
  let module = {
    exports: {}
  };

  /*
 *  Sugar Custom 2021.05.19
 *
 *  Freely distributable and licensed under the MIT-style license.
 *  Copyright (c)  Andrew Plummer
 *  https://sugarjs.com/
 *
 * ---------------------------- */
(function(){'use strict';function H(a,b){for(var c in a)if(K(a,c)&&!1===b.call(a,a[c],c,a))break}function wa(a){function b(e,h,k){F(d,e,function(l,f,m){l=la(l,f,m);Ta(d,l.methods,h,k,l.m);return d})}var c="Object"===a,d=xa(a,!0);b("defineStatic",1);b("defineInstance",2);b("defineInstanceAndStatic",3);b("defineStaticWithArguments",1,!0);b("defineInstanceWithArguments",2,!0);F(d,"defineStaticPolyfill",function(e,h,k){e=la(e,h,k);ca(S[a],e.methods,!0,e.m);return d});F(d,"defineInstancePolyfill",function(e,h,k){e=
la(e,h,k);ca(S[a].prototype,e.methods,!0,e.m);H(e.methods,function(l,f){da(d,f,l)});return d});F(d,"alias",function(e,h){var k=d,l="string"===typeof h?d[h]:h;k[e]=l;l.instance&&da(k,e,l.instance,!0);return d});F(d,"extend",function(e){function h(p,v){var y=e[p];if(y)for(var x=0,w;w=y[x];x++)if(w===v)return!0;return!1}function k(p,v){return e[p]&&!h(p,v)}function l(p,v,y){var x;if(x=!(c&&y===m&&(!ya||"get"===p||"set"===p))){a:if(v=v.flags,y[p]&&v){for(y=0;y<v.length;y++)if(!1===e[v[y]]){y=!0;break a}y=
void 0}else y=!1;x=!y}return x&&!h("except",p)}var f=S[a],m=f.prototype,q={},r={};e=e||{};var n=e.methods;if(!h("except",f)&&!k("namespaces",f))return c&&"boolean"===typeof e.objectPrototype&&(ya=e.objectPrototype),H(n||d,function(p,v){n&&(v=p,p=d[v]);K(p,"instance")&&l(v,p,m)&&(r[v]=p.instance);K(p,"static")&&l(v,p,f)&&(q[v]=p)}),ca(f,q),ca(m,r),n||F(d,"active",!0),d});ea[a]=d;za["[object "+a+"]"]=d;ma(a);Ua(d);return B[a]=d}function Va(){return"Sugar"}function Ta(a,b,c,d,e){H(b,function(h,k){var l=
h;d&&(l=Aa(h));e&&(l.flags=e);if(c&2&&!h.instance){var f=d?Aa(h,!0):Wa(h);F(l,"instance",f)}c&1&&F(l,"static",!0);f=l;a[k]=f;f.instance&&da(a,k,f.instance,!0);a.active&&a.extend(k)})}function la(a,b,c){if("string"===typeof a){var d={};d[a]=b;a=c}else d=a,a=b;return{m:a,methods:d}}function Aa(a,b){var c=a.length-1-(b?1:0);return function(){var d=[],e=[];b&&d.push(this);var h=Math.max(arguments.length,c);for(var k=0;k<h;k++)k<c?d.push(arguments[k]):e.push(arguments[k]);d.push(e);return a.apply(this,
d)}}function Wa(a){switch(a.length){case 0:case 1:return function(){return a(this)};case 2:return function(b){return a(this,b)};case 3:return function(b,c){return a(this,b,c)};case 4:return function(b,c,d){return a(this,b,c,d)};case 5:return function(b,c,d,e){return a(this,b,c,d,e)}}}function ca(a,b,c,d){H(b,function(e,h){c&&!d&&a[h]||F(a,h,e)})}function xa(a){function b(c,d){if(!(this instanceof b))return new b(c,d);this.constructor!==b&&(c=this.constructor.apply(c,arguments));this.raw=c}F(b,"toString",
function(){return"Sugar"+a});F(b.prototype,"valueOf",function(){return this.raw});return b}function da(a,b,c){c=Xa(c);var d;var e=Ba.prototype;var h=(d=e[b])&&d!==Object.prototype[b];d&&d.B||(e[b]=h?Ya(b):c);a.prototype[b]=c;a===B.Object&&Za(b,c)}function Ua(a){H(B.Object&&B.Object.prototype,function(b,c){if("function"===typeof b){var d=a.prototype;K(d,c)||(d[c]=b)}})}function Za(a,b){H(ea,function(c){c=c.prototype;K(c,a)||(c[a]=b)})}function Xa(a){return function(){return new Ba(a.apply(this.raw,
arguments))}}function Ya(a){function b(){var c=this.raw,d;null!=c&&(d=za[fa(c)]);d||(d=B.Object);return(new d(c))[a].apply(this,arguments)}b.B=!0;return b}function ma(a,b){var c=ea[a],d=S[a].prototype;!b&&Ca&&(b=Ca(d));H(b,function(e){if("constructor"!==e&&"valueOf"!==e&&"__proto__"!==e){try{var h=d[e];if("function"!==typeof h)return}catch(k){return}da(c,e,h)}})}function $a(a,b,c){a[b]=c.value}function F(a,b,c,d){na(a,b,{value:c,enumerable:!!d,configurable:!0,writable:!0})}function fa(a){return ab.call(a)}
function K(a,b){return!!a&&bb.call(a,b)}function A(a,b){if(K(a,b))return a[b]}function oa(a,b,c){c||(c=fa(a));return c==="[object "+b+"]"}function Q(a){return function(b,c,d){b[a](c,d)}}function cb(a,b,c){F(a,b,c)}function C(a){return void 0!==a}function pa(a,b){if(K(a,b))return b}function N(a,b){H(b,function(c,d){a[d]=c});return a}function db(a,b,c,d){var e=[],h;for(h in a)h>>>0==h&&4294967295!=h&&(c||(d?h<=b:h>=b))&&e.push(+h);e.sort(function(k,l){var f=k>b;return f!==l>b?f?-1:1:k-l});return e}
function O(a,b){for(var c=0,d=a.length;c<d;c++){if(!(c in a)){d=a;for(var e=b,h=db(d,c,void 0),k=0,l=h.length;k<l;k++)c=h[k],e.call(d,d[c],c,d);return d}b(a[c],c)}}function eb(a,b){for(var c=[],d=0,e=a.length;d<e;d++){var h=a[d];d in a&&b(h,d)&&c.push(h)}return c}function ha(a,b){for(var c=[],d=0,e=a.length;d<e;d++)d in a&&c.push(b(a[d],d));return c}function fb(a){T(a)||(a=String(a));return a.replace(/([\\\/'*+?|()\[\]{}.^$-])/g,"\\$1")}function G(a,b){return a["get"+(L(a)?"UTC":"")+b]()}function P(a,
b,c,d){if(!d||c!==G(a,b,c))a["set"+(L(a)?"UTC":"")+b](c)}function qa(){return gb("newDateInternal")()}function Y(a,b,c){if(U(b)){var d=G(a,"Day");if(c){c=0<c?1:-1;var e=b%7-d;e&&e/Da(e)!==c&&(b+=7*c)}b=G(a,"Date")+b-d;P(a,"Date",b);return a.getTime()}}function Ea(a,b,c){c=c||0;for(void 0===b&&(b=7);b>=c&&!1!==a(Z[b],b);b--);}function hb(a,b){for(;0<=a&&!1!==b(Z[a],a);)a=aa(a)}function aa(a){return 6===a?4:5===a?3:a-1}function ra(a,b,c,d){Ea(function(e,h){var k=e.name;var l=A(a,sa(a,k));C(l)&&b(k,
l,e,h);k=void 0;!1!==k&&4===h&&(k=A(a,sa(a,"weekday")),C(k)&&b("weekday",k,e,h),k=void 0);return k},c,d)}function ib(a,b){ra(a,b,7,4)}function Fa(a,b){Y(a,7*Ga((G(a,"Day")-b)/7)+b);return a}function Ha(a,b,c){5===b&&Fa(a,ia.get(c).u());return R(a,aa(b))}function R(a,b,c,d){hb(b,function(e,h){var k=d?e.end:e.start;Ia(k)&&(k=k(a));P(a,e.method,k);return!C(c)||h>c});return a}function sa(a,b){return pa(a,b)||pa(a,b+"s")||"day"===b&&pa(a,"date")}function Ja(a,b,c){return jb(null,a,b,c).date}function jb(a,
b,c,d){function e(t,u){var z=A(x,"params")||{};O(u.to,function(D,V){var E=t[V+1];if(E){if("yy"===D||"y"===D){D="year";var I=A(x,"prefer");E=+E;E+=50>E?2E3:1900;if(I){var J=E-G(w,"FullYear");J/Da(J)!==I&&(E+=100*I)}}else(I=A(ta,D))?(D=I.g||D,J=I.s?I.s:I.sign?"+"===E?1:-1:I.I?!!J:+E.replace(/,/,"."),"month"===I.g&&--J,E=J):E=n.F(D,E);z[D]=E}});return z}function h(t,u){L(t)&&!C(A(x,"fromUTC"))&&(x.fromUTC=!0);L(t)&&!C(A(x,"setUTC"))&&(x.setUTC=!0);u&&(t=new Date(t.getTime()));return t}function k(){O(y,
function(t){t.call()})}function l(t){t=t.toLowerCase();n=ia.get(A(x,"locale"));for(var u=0,z,D;z=n.compiledFormats[u];u++)if(D=t.match(z.reg)){n.A(z,u);g=e(D,z);if(C(g.timestamp)){t=g.timestamp;g=null;break}C(g.ampm)&&(u=g.ampm,1===u&&12>g.hour?g.hour+=12:0===u&&12===g.hour&&(g.hour=0));if(g.utc||C(g.tzHour))if(u=g.tzHour,z=g.tzMinute,D=g.tzSign,L(w,!0),u=(D||1)*(60*(u||0)+(z||0)))g.minute=(g.minute||0)-u;C(g.shift)&&void 0===g.unit&&(C(g.month)?g.unit=7:C(g.weekday)&&(g.unit=5));C(g.num)&&void 0===
g.unit&&(u=g.num,C(g.weekday)?q(u):C(g.month)&&(g.date=g.num));g.midday&&f(g.midday);C(g.day)&&(R(w,3),void 0===g.unit&&(g.unit=4,g.num=g.day,delete g.day));C(g.unit)&&(u=g.unit,z=C(g.num)?g.num:1,C(g.weekday)&&(6===u?(q(z),z=1):(W(w,{weekday:g.weekday},!0),delete g.weekday)),g.half&&(z*=g.half),C(g.shift)?z*=g.shift:g.sign&&(z*=g.sign),C(g.day)&&(z+=g.day,delete g.day),r(u),g[ua.units[u]]=z,p=!0);g.edge&&m(g.edge,g);g.yearSign&&(g.year*=g.yearSign);break}g?p?W(w,g,!1,1):(L(w)&&R(w,3),W(w,g,!0,0,
A(x,"prefer"),v)):(w=new Date(t),A(x,"fromUTC")&&w.setTime(w.getTime()+6E4*w.getTimezoneOffset()));k();return w}function f(t){g.hour=t%24;23<t&&y.push(function(){var u=w,z=Ka(t/24),D={};D.date=z;W(u,D,void 0,1)})}function m(t,u){var z=u.unit;z||ib(u,function(V,E,I,J){"weekday"===V&&C(u.month)||(z=J)});if(6===z&&C(u.weekday)){var D=u.weekday;delete u.weekday}y.push(function(){if(0>t)Ha(w,z,A(x,"locale"));else if(0<t){if(1===t){var V=4;Ha(w,4)}var E=w,I=z,J=A(x,"locale");5===I&&(J=ia.get(J).u()-1,Y(E,
7*La((G(E,"Day")-J)/7)+J));R(E,aa(I),V,!0)}C(D)&&(Y(w,D,-t),R(w,3))});u.specificity=6===z?4:z-1}function q(t){g.weekday=7*(t-1)+g.weekday;v=g.date=1}function r(t){var u;ra(g,function(z,D,V,E){if(E>=t)return w.setTime(NaN),!1;E<t&&(u=u||{},u[z]=D,delete g[sa(g,z)])});u&&(y.push(function(){W(w,u,!0,!1,A(x,"prefer"),v)}),g.edge&&(m(g.edge,u),delete g.edge))}var n,p,v;var y=[];var x=function(t){t=T(t)?{locale:t}:t||{};t.prefer=+!!A(t,"future")-+!!A(t,"past");return t}(c);var w=a&&b?h(a,!0):qa();L(w,A(x,
"fromUTC"));if(T(b))w=l(b);else if(Ma(b))w=h(b,K(x,"clone")||d);else if(b&&"object"===typeof b){var g=N({},b);W(w,g,!0)}else(U(b)||null===b)&&w.setTime(b);L(w,!!A(x,"setUTC"));return{set:g,date:w}}function W(a,b,c,d,e,h){function k(){var m=Z[f];d=e;l(m.name,1,m,f)}function l(m,q,r,n){var p=r.method,v;e&&!f&&(f="weekday"===m?5:4===n?6:n+1);n>b.specificity||(b.specificity=n);if(v=q%1){if(n){var y=Z[aa(n)];v=kb(r.h/y.h*v);b[y.name]=v}q=Ka(q)}"weekday"===m?d||Y(a,q,h):(m=6===n&&28<G(a,"Date"),d&&!r.l?
a.setTime(a.getTime()+q*d*r.h):(d&&(5===n&&(q*=7,p=Z[4].method),q=q*d+G(a,p)),r=p,p=q,n=d,"ISOWeek"===r?U(p)&&(n=new Date(a.getTime()),L(n,!!L(a)),r=G(a,"Day"),R(n,6),P(n,"Date",4),Fa(n,1),p=G(n,"Date")+7*(p-1),P(n,"Date",p),p=G(n,"FullYear"),P(a,"FullYear",p),p=G(n,"Month"),P(a,"Month",p),n=G(n,"Date"),P(a,"Date",n),Y(a,r||7)):P(a,r,p,n),m&&(0>q&&(q=q%12+12),m=q%12!==G(a,"Month")),m&&P(a,"Date",0)))}var f;if(U(b)&&d)b={millisecond:b};else if(U(b))return a.setTime(b),a;ra(b,l);c&&b.specificity&&R(a,
aa(b.specificity));a:{if(f&&!(7<f))switch(e){case -1:c=a>qa();break a;case 1:c=a<qa();break a}c=void 0}c&&k();return a}function ja(a){var b=a.join("");return a&&a.length?b.length===a.length?"["+b+"]":ha(a,fb).join("|"):""}function M(a,b){1<a.length&&(a="(?:"+a+")");b&&(a+="?");return a}function lb(a,b,c){a=Na[a];return b=a.o?M(b+M(c)):a.v?b+M(a.v+"|"+c):b+M(c,!0)}function Oa(a){function b(c){this.G(c)}b.prototype={F:function(c,d){var e=this[c+"Map"],h;e&&(h=e[d]);void 0===h&&(h=this.C(d),"month"===
c&&--h);return h},C:function(c){var d=this.numeralMap[c];if(C(d))return d;d=+c.replace(/,/,".");if(!isNaN(d))return d;d=this.D(c);isNaN(d)||(this.numeralMap[c]=d);return d},D:function(c){var d=1,e=0,h;var k=c.split("");for(var l=k.length-1;h=k[l];l--){c=A(this.numeralMap,h);void 0===c&&(c=A(X,h)||0);(h=0<c&&0===c%10)?(f&&(e+=d),l?d=c:e+=c):(e+=c*d,d*=10);var f=h}return e},u:function(){var c=this.firstDayOfWeek;return C(c)?c:1},A:function(c,d){this.compiledFormats.splice(d,1);this.compiledFormats.unshift(c)},
addFormat:function(c,d){function e(l){var f,m=l.match(/\?$/),q=l.match(/^(\d+)\??$/),r=l.match(/(\d)(?:-(\d))?/),n=l.replace(/[^a-z]+$/i,"");if(f=A(k.parsingAliases,n))return l=h(f),m&&(l=M(l,!0)),l;if(q)l=k.tokens[q[1]];else if(f=A(ta,n))l=f.src;else if(f=A(k.parsingTokens,n)||A(k,n),n=n.replace(/s$/,""),f||(f=A(k.parsingTokens,n)||A(k,n+"s")),T(f)){l=f;var p=k[n+"Suffix"]}else r&&(f=eb(f,function(v,y){var x=y%(k.units?8:f.length);return x>=r[1]&&x<=(r[2]||r[1])})),l=ja(f);if(!l)return"";q?l=M(l):
(d.push(n),l="("+l+")");p&&(l=lb(n,l,p));m&&(l+="?");return l}function h(l){l=l.replace(/ /g," ?");return l.replace(/\{([^,]+?)\}/g,function(f,m){var q=m.split("|");return 1<q.length?M(ha(q,e).join("|")):e(m)})}var k=this;d||(d=[],c=h(c));k.addRawFormat(c,d)},addRawFormat:function(c,d){this.compiledFormats.unshift({reg:RegExp("^ *"+c+" *$","i"),to:d})},G:function(c){function d(m,q,r,n){var p=m,v=[];f[p]||(p+="s");if(!r){r={};var y=!0}e(p,function(x,w,g){w=w*q+g;g=n?n(g):g;r[x]=g;r[x.toLowerCase()]=
g;v[w]=x});f[p]=v;y&&(f[m+"Map"]=r)}function e(m,q){O(f[m],function(r,n){h(r,function(p,v){q(p,v,n)})})}function h(m,q){var r=ha(m.split("+"),function(n){return n.replace(/(.+):(.+)$/,function(p,v,y){return ha(y.split("|"),function(x){return v+x}).join("|")})}).join("|");O(r.split("|"),q)}function k(m,q,r){O(f[m],function(n){q&&(n=l(n,r));f.addFormat(n)})}function l(m,q){if(q)var r=M("{time}[,\\s\\u3000]",!0)+m;else{r=",?[\\s\\u3000]";var n;(n=ja(f.timeMarkers))&&(r+="| (?:"+n+") ");r=M(r,f.timeMarkerOptional);
r=M(r+"{time}",!0);r=m+r}return r}var f=this;f.compiledFormats=[];f.parsingAliases={};f.parsingTokens={};N(f,c);(function(){O(mb,function(m){var q=f[m];T(q)?f[m]=q.split(","):q||(f[m]=[])})})();d("month",12);d("weekday",7);d("unit",8);d("ampm",2);(function(){var m={};d("numeral",10,m);d("article",1,m,function(){return 1});d("placeholder",4,m,function(q){return nb(10,q+1)});f.numeralMap=m})();f.parsingAliases.time=f.ampmFront?"{ampm?} {hour} (?:{minute} (?::?{second})?)?":f.ampm.length?"{hour}(?:[.:]{minute}(?:[.:]{second})? {ampm?}| {ampm})":
"{hour}(?:[.:]{minute}(?:[.:]{second})?)";f.parsingAliases.tzOffset="(?:{Z}|{GMT?}(?:{tzSign}{tzHour}(?::?{tzMinute}(?: \\([\\w\\s]+\\))?)?)?)?";(function(){H(Na,function(m,q){var r=m.i?ta[m.i].src:m.src;if(m.H||f.numeralUnits){var n="";var p=f.numerals.concat(f.placeholders).concat(f.articles);f.allowsFullWidth&&(p=p.concat(Pa.split("")));p.length&&(n="|(?:"+ja(p)+")+");r+=n}(p=f[q+"s"])&&p.length&&(r+="|"+ja(p));f.parsingTokens[q]=r})})();(function(){Ea(function(m,q){var r=f.timeSuffixes[q];r&&
(f[(m.alias||m.name)+"Suffix"]=r)})})();(function(){O(f.modifiers,function(m){var q=m.name,r=q+"Map";var n=f[r]||{};h(m.src,function(p,v){var y=A(f.parsingTokens,q),x=m.value;n[p]=x;f.parsingTokens[q]=y?y+"|"+p:p;"sign"===m.name&&0===v&&(f[1===x?"fromNow":"ago"]=p)});f[r]=n})})();(function(){O(ob,function(m){var q=m.src;m.mdy&&f.mdy&&(q=m.mdy);m.time?(f.addFormat(l(q,!0)),f.addFormat(l(q))):f.addFormat(q)});f.addFormat("{time}")})();k("parse");k("timeParse",!0);k("timeFrontParse",!0,!0)}};return new b(a)}
var B,S="undefined"!==typeof global&&global.Object===Object?global:this,pb="undefined"!==typeof module&&module.exports,ya=!1,ea={},za={},na=Object.defineProperty&&Object.defineProperties?Object.defineProperty:$a,Ba=xa("Chainable"),Ca=Object.getOwnPropertyNames,ab=Object.prototype.toString,bb=Object.prototype.hasOwnProperty;(function(){B=S.Sugar;if(!B){B=function(a){H(B,function(b,c){K(ea,c)&&b.extend(a)});return B};if(pb)module.exports=B;else try{S.Sugar=B}catch(a){}H("Object Number String Array Date RegExp Function".split(" "),
function(a){wa(a)});F(B,"extend",B);F(B,"toString",Va);F(B,"createNamespace",wa);F(B,"util",{hasOwn:K,getOwn:A,setProperty:F,classToString:fa,defineProperty:na,forEachProperty:H,mapNativeToChainable:ma})}})();var va=B.Date;K=B.util.hasOwn;A=B.util.getOwn;F=B.util.setProperty;fa=B.util.classToString;na=B.util.defineProperty;H=B.util.forEachProperty;ma=B.util.mapNativeToChainable;var U,T,Ma,Ia;Q("alias");var ka=Q("defineStatic");Q("defineInstance");Q("defineStaticPolyfill");Q("defineInstancePolyfill");
Q("defineInstanceAndStatic");Q("defineInstanceWithArguments");var Ka=Math.trunc||function(a){return 0!==a&&isFinite(a)?0>a?La(a):Ga(a):a},X,Pa,Da=Math.abs,nb=Math.pow,La=Math.ceil,Ga=Math.floor,kb=Math.round,Qa=String.fromCharCode,L=function(a){var b="_sugar_"+a;return function(c,d){return 1<arguments.length?(F(c,b,d),c):c[b]}}("utc");(function(){function a(e,h){return h&&oa(new h,"Object")?b(h):c(e)}function b(e){var h=String(e);return function(k){return String(k.constructor)===h}}function c(e){return function(h,
k){return oa(h,e,k)}}function d(e){var h=e.toLowerCase();return function(k){var l=typeof k;return l===h||"object"===l&&oa(k,e)}}(function(){var e="Boolean Number String Date RegExp Function Array Error Set Map".split(" ");d(e[0]);U=d(e[1]);T=d(e[2]);Ma=a(e[3]);a(e[4]);Ia=a(e[5]);Array.isArray||a(e[6]);a(e[7]);a(e[8],"undefined"!==typeof Set&&Set);a(e[9],"undefined"!==typeof Map&&Map)})();(function(){O("Int8 Uint8 Uint8Clamped Int16 Uint16 Int32 Uint32 Float32 Float64".split(" "),function(){})})()})();
(function(){var a="";X={};for(var b=0,c;9>=b;b++)c=Qa(b+65296),a+=c,X[c]=Qa(b+48);X[","]="";X["\uff0e"]=".";X["."]=".";Pa=a})();var mb="months weekdays units numerals placeholders articles tokens timeMarkers ampm timeSuffixes parse timeParse timeFrontParse modifiers".split(" "),ta={yyyy:{g:"year",src:"\\d{4}"},MM:{g:"month",src:"[01]?\\d"},dd:{g:"date",src:"[0123]?\\d"},hh:{g:"hour",src:"[0-2]?\\d"},mm:{g:"minute",src:"[0-5]\\d"},ss:{g:"second",src:"[0-5]\\d(?:[,.]\\d+)?"},yy:{g:"year",src:"\\d{2}"},
y:{g:"year",src:"\\d"},yearSign:{src:"[+-]",sign:!0},tzHour:{src:"[0-1]\\d"},tzMinute:{src:"[0-5]\\d"},tzSign:{src:"[+\u2212-]",sign:!0},ihh:{g:"hour",src:"[0-2]?\\d(?:[,.]\\d+)?"},imm:{g:"minute",src:"[0-5]\\d(?:[,.]\\d+)?"},GMT:{g:"utc",src:"GMT",s:1},Z:{g:"utc",src:"Z",s:1},timestamp:{src:"\\d+"}},Na={year:{i:"yyyy",o:!0},month:{i:"MM",o:!0},date:{i:"dd",o:!0},hour:{i:"hh",v:":"},minute:{i:"mm"},second:{i:"ss"},num:{src:"\\d+",H:!0}},ob=[{src:"{MM}[-.\\/]{yyyy}"},{time:!0,src:"{dd}[-.\\/]{MM}(?:[-.\\/]{yyyy|yy|y})?",
mdy:"{MM}[-.\\/]{dd}(?:[-.\\/]{yyyy|yy|y})?"},{time:!0,src:"{yyyy}[-.\\/]{MM}(?:[-.\\/]{dd})?"},{src:"\\\\/Date\\({timestamp}(?:[+-]\\d{4,4})?\\)\\\\/"},{src:"{yearSign?}{yyyy}(?:-?{MM}(?:-?{dd}(?:T{ihh}(?::?{imm}(?::?{ss})?)?)?)?)?{tzOffset?}"}],Z=[{name:"millisecond",method:"Milliseconds",h:1,start:0,end:999},{name:"second",method:"Seconds",h:1E3,start:0,end:59},{name:"minute",method:"Minutes",h:6E4,start:0,end:59},{name:"hour",method:"Hours",h:36E5,start:0,end:23},{name:"day",alias:"date",method:"Date",
l:!0,h:864E5,start:1,end:function(a){return 32-G(new Date(G(a,"FullYear"),G(a,"Month"),32),"Date")}},{name:"week",method:"ISOWeek",l:!0,h:6048E5},{name:"month",method:"Month",l:!0,h:26298E5,start:0,end:11},{name:"year",method:"FullYear",l:!0,h:315576E5,start:0}],gb=function(a,b){function c(e){return d[e]}var d=N({},b);F(a,"getOption",c);cb(a,"setOption",function(e,h){if(1===arguments.length)var k=e;else k={},k[e]=h;H(k,function(l,f){null===l&&(l=b[f]);d[f]=l})});return c}(va,{newDateInternal:function(){return new Date}}),
ua,ia;ka(va,{create:function(a,b){return Ja(a,b)}});var ba={code:"en",plural:!0,timeMarkers:"at",ampm:"AM|A.M.|a,PM|P.M.|p",units:"millisecond:|s,second:|s,minute:|s,hour:|s,day:|s,week:|s,month:|s,year:|s",months:"Jan:uary|,Feb:ruary|,Mar:ch|,Apr:il|,May,Jun:e|,Jul:y|,Aug:ust|,Sep:tember|t|,Oct:ober|,Nov:ember|,Dec:ember|",weekdays:"Sun:day|,Mon:day|,Tue:sday|,Wed:nesday|,Thu:rsday|,Fri:day|,Sat:urday|+weekend",numerals:"zero,one|first,two|second,three|third,four:|th,five|fifth,six:|th,seven:|th,eight:|h,nin:e|th,ten:|th",
articles:"a,an,the",tokens:"the,st|nd|rd|th,of|in,a|an,on",time:"{H}:{mm}",past:"{num} {unit} {sign}",future:"{num} {unit} {sign}",duration:"{num} {unit}",modifiers:[{name:"half",src:"half",value:.5},{name:"midday",src:"noon",value:12},{name:"midday",src:"midnight",value:24},{name:"day",src:"yesterday",value:-1},{name:"day",src:"today|tonight",value:0},{name:"day",src:"tomorrow",value:1},{name:"sign",src:"ago|before",value:-1},{name:"sign",src:"from now|after|from|in|later",value:1},{name:"edge",
src:"first day|first|beginning",value:-2},{name:"edge",src:"last day",value:1},{name:"edge",src:"end|last",value:2},{name:"shift",src:"last",value:-1},{name:"shift",src:"the|this",value:0},{name:"shift",src:"next",value:1}],parse:"(?:just)? now;{shift} {unit:5-7};{months?} (?:{year}|'{yy});{midday} {4?} {day|weekday};{months},?(?:[-.\\/\\s]{year})?;{edge} of (?:day)? {day|weekday};{0} {num}{1?} {weekday} {2} {months},? {year?};{shift?} {day?} {weekday?} {timeMarker?} {midday};{sign?} {3?} {half} {3?} {unit:3-4|unit:7} {sign?};{0?} {edge} {weekday?} {2} {shift?} {unit:4-7?} {months?},? {year?}".split(";"),
timeParse:"{day|weekday};{shift} {unit:5?} {weekday};{0?} {date}{1?} {2?} {months?};{weekday} {2?} {shift} {unit:5};{0?} {num} {2?} {months}\\.?,? {year?};{num?} {unit:4-5} {sign} {day|weekday};{year}[-.\\/\\s]{months}[-.\\/\\s]{date};{0|months} {date?}{1?} of {shift} {unit:6-7};{0?} {num}{1?} {weekday} of {shift} {unit:6};{date}[-.\\/\\s]{months}[-.\\/\\s](?:{year}|'?{yy});{weekday?}\\.?,? {months}\\.?,? {date}{1?},? (?:{year}|'{yy})?".split(";"),timeFrontParse:["{sign} {num} {unit}","{num} {unit} {sign}",
"{4?} {day|weekday}"]},Ra=N(N({},ba),{mdy:!0,firstDayOfWeek:0,firstDayOfWeekYear:1,"short":"{MM}/{dd}/{yyyy}",medium:"{Month} {d}, {yyyy}","long":"{Month} {d}, {yyyy} {time}",full:"{Weekday}, {Month} {d}, {yyyy} {time}",stamp:"{Dow} {Mon} {d} {yyyy} {time}",time:"{h}:{mm} {TT}"});ka=N(N({},ba),{"short":"{dd}/{MM}/{yyyy}",medium:"{d} {Month} {yyyy}","long":"{d} {Month} {yyyy} {H}:{mm}",full:"{Weekday}, {d} {Month}, {yyyy} {time}",stamp:"{Dow} {d} {Mon} {yyyy} {time}"});ba=N(N({},ba),{"short":"{yyyy}-{MM}-{dd}",
medium:"{d} {Month}, {yyyy}","long":"{d} {Month}, {yyyy} {H}:{mm}",full:"{Weekday}, {d} {Month}, {yyyy} {time}",stamp:"{Dow} {d} {Mon} {yyyy} {time}"});var Sa={"en-US":Ra,"en-GB":ka,"en-AU":ka,"en-CA":ba};(function(){function a(b){this.j={};this.add(b)}a.prototype={get:function(b,c){var d=this.j[b];!d&&Sa[b]?d=this.add(b,Sa[b]):!d&&b&&(d=this.j[b.slice(0,2)]);return d||!1===c?d:this.current},getAll:function(){return this.j},set:function(b){var c=this.get(b,!1);if(!c)throw new TypeError("Invalid Locale: "+
b);return this.current=c},add:function(b,c){c?c.code=b:(c=b,b=c.code);var d=c.compiledFormats?c:Oa(c);this.j[b]=d;this.current||(this.current=d);return d},remove:function(b){this.current.code===b&&(this.current=this.get("en"));return delete this.j[b]}};ua=Oa(Ra);ia=new a(ua)})();(function(a,b){a.prototype.constructor=function(){return b.apply(this,arguments)}})(va,Ja)}).call(this);
Sugar = module.exports;
}
